version: '3'
networks:
    laravel:
        driver: bridge
services:
    nginx:
        image: nginx:alpine
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel
    app:
        build: ./docker/app
        volumes:
            - ./:/var/www/:cached
        working_dir: /var/www
        environment:
            APP_URL: http://laraweb.test
            MIX_APP_URL_API: http://laraweb.test/api
        depends_on:
            - db
            - redis
        networks:
            - laravel
        container_name: "laraweb-app"
    redis:
        image: redis:latest
        volumes:
            - ./docker/redis/data:/data
        ports:
            - 6379:6379
        command: redis-server --appendonly yes
        container_name: "laraweb-redis"
        networks:
            - laravel
    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lara_db
            MYSQL_USER: lara
            MYSQL_PASSWORD: password
        ports:
            - "3308:3306"
        volumes:
            - ./docker/mysql/db-data:/var/lib/mysql:cached
            - ./docker/mysql/mysql_confd:/etc/mysql/conf.d:cached
        networks:
            - laravel
        container_name: "laraweb-db"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "phpadmin_lara"
        ports:
          - "8080:80"
        volumes:
          - /sessions
        depends_on:
          - db
        networks:
            - laravel
    mailhog:
        image: mailhog/mailhog
        ports:
            - "8065:8025"
        networks:
            - laravel
volumes:
    db-data:
